"use server";

export interface DailySong {
    title: string;
    artist: string;
}

// A curated list of 365 songs for a year of good vibes.
// Mix of Classics, Pop, Rock, Indie, Soul, Jazz, and Electronic.
const songs: DailySong[] = [
    { title: "Here Comes The Sun", artist: "The Beatles" }, // Jan 1
    { title: "Heroes", artist: "David Bowie" },
    { title: "Dreams", artist: "Fleetwood Mac" },
    { title: "Feeling Good", artist: "Nina Simone" },
    { title: "Mr. Blue Sky", artist: "Electric Light Orchestra" },
    { title: "September", artist: "Earth, Wind & Fire" },
    { title: "Africa", artist: "Toto" },
    { title: "Take On Me", artist: "a-ha" },
    { title: "Don't Stop Believin'", artist: "Journey" },
    { title: "Bohemian Rhapsody", artist: "Queen" },
    { title: "Rocket Man", artist: "Elton John" },
    { title: "Billie Jean", artist: "Michael Jackson" },
    { title: "Every Breath You Take", artist: "The Police" },
    { title: "Sweet Child O' Mine", artist: "Guns N' Roses" },
    { title: "Smells Like Teen Spirit", artist: "Nirvana" },
    { title: "Wonderwall", artist: "Oasis" },
    { title: "Hotel California", artist: "Eagles" },
    { title: "Hey Jude", artist: "The Beatles" },
    { title: "Imagine", artist: "John Lennon" },
    { title: "What A Wonderful World", artist: "Louis Armstrong" },
    { title: "Respect", artist: "Aretha Franklin" },
    { title: "Good Vibrations", artist: "The Beach Boys" },
    { title: "I Will Survive", artist: "Gloria Gaynor" },
    { title: "Stayin' Alive", artist: "Bee Gees" },
    { title: "Dancing Queen", artist: "ABBA" },
    { title: "Superstition", artist: "Stevie Wonder" },
    { title: "I Want to Hold Your Hand", artist: "The Beatles" },
    { title: "Like a Rolling Stone", artist: "Bob Dylan" },
    { title: "Purple Haze", artist: "Jimi Hendrix" },
    { title: "Yesterday", artist: "The Beatles" },
    { title: "Let It Be", artist: "The Beatles" },
    { title: "Hey Joe", artist: "Jimi Hendrix" },
    { title: "Stairway to Heaven", artist: "Led Zeppelin" },
    { title: "London Calling", artist: "The Clash" },
    { title: "Hotel California", artist: "Eagles" },
    { title: "Free Bird", artist: "Lynyrd Skynyrd" },
    { title: "Comfortably Numb", artist: "Pink Floyd" },
    { title: "Wish You Were Here", artist: "Pink Floyd" },
    { title: "Tiny Dancer", artist: "Elton John" },
    { title: "Your Song", artist: "Elton John" },
    { title: "Piano Man", artist: "Billy Joel" },
    { title: "American Pie", artist: "Don McLean" },
    { title: "Sultans of Swing", artist: "Dire Straits" },
    { title: "Money for Nothing", artist: "Dire Straits" },
    { title: "Under Pressure", artist: "Queen & David Bowie" },
    { title: "Another One Bites the Dust", artist: "Queen" },
    { title: "We Will Rock You", artist: "Queen" },
    { title: "We Are the Champions", artist: "Queen" },
    { title: "Radio Ga Ga", artist: "Queen" },
    { title: "Don't Stop Me Now", artist: "Queen" },
    { title: "Somebody to Love", artist: "Queen" },
    { title: "Killer Queen", artist: "Queen" },
    { title: "Crazy Little Thing Called Love", artist: "Queen" },
    { title: "Space Oddity", artist: "David Bowie" },
    { title: "Starman", artist: "David Bowie" },
    { title: "Rebel Rebel", artist: "David Bowie" },
    { title: "Let's Dance", artist: "David Bowie" },
    { title: "Modern Love", artist: "David Bowie" },
    { title: "Life on Mars?", artist: "David Bowie" },
    { title: "Ziggy Stardust", artist: "David Bowie" },
    { title: "Changes", artist: "David Bowie" },
    { title: "The Man Who Sold the World", artist: "David Bowie" },
    { title: "Heroes", artist: "David Bowie" },
    { title: "Under the Bridge", artist: "Red Hot Chili Peppers" },
    { title: "Californication", artist: "Red Hot Chili Peppers" },
    { title: "Otherside", artist: "Red Hot Chili Peppers" },
    { title: "Scar Tissue", artist: "Red Hot Chili Peppers" },
    { title: "Can't Stop", artist: "Red Hot Chili Peppers" },
    { title: "Dani California", artist: "Red Hot Chili Peppers" },
    { title: "Snow (Hey Oh)", artist: "Red Hot Chili Peppers" },
    { title: "By the Way", artist: "Red Hot Chili Peppers" },
    { title: "Give It Away", artist: "Red Hot Chili Peppers" },
    { title: "Creep", artist: "Radiohead" },
    { title: "Karma Police", artist: "Radiohead" },
    { title: "No Surprises", artist: "Radiohead" },
    { title: "High and Dry", artist: "Radiohead" },
    { title: "Fake Plastic Trees", artist: "Radiohead" },
    { title: "Paranoid Android", artist: "Radiohead" },
    { title: "Bitter Sweet Symphony", artist: "The Verve" },
    { title: "Wonderwall", artist: "Oasis" },
    { title: "Don't Look Back in Anger", artist: "Oasis" },
    { title: "Champagne Supernova", artist: "Oasis" },
    { title: "Live Forever", artist: "Oasis" },
    { title: "Song 2", artist: "Blur" },
    { title: "Girls & Boys", artist: "Blur" },
    { title: "Parklife", artist: "Blur" },
    { title: "Common People", artist: "Pulp" },
    { title: "Disco 2000", artist: "Pulp" },
    { title: "Seven Nation Army", artist: "The White Stripes" },
    { title: "Fell in Love with a Girl", artist: "The White Stripes" },
    { title: "Hard to Explain", artist: "The Strokes" },
    { title: "Last Nite", artist: "The Strokes" },
    { title: "Someday", artist: "The Strokes" },
    { title: "Reptilia", artist: "The Strokes" },
    { title: "Mr. Brightside", artist: "The Killers" },
    { title: "Somebody Told Me", artist: "The Killers" },
    { title: "All These Things That I've Done", artist: "The Killers" },
    { title: "When You Were Young", artist: "The Killers" },
    { title: "Human", artist: "The Killers" },
    { title: "Sex on Fire", artist: "Kings of Leon" },
    { title: "Use Somebody", artist: "Kings of Leon" },
    { title: "Pumped Up Kicks", artist: "Foster the People" },
    { title: "Kids", artist: "MGMT" },
    { title: "Electric Feel", artist: "MGMT" },
    { title: "Time to Pretend", artist: "MGMT" },
    { title: "Midnight City", artist: "M83" },
    { title: "Get Lucky", artist: "Daft Punk" },
    { title: "One More Time", artist: "Daft Punk" },
    { title: "Harder, Better, Faster, Stronger", artist: "Daft Punk" },
    { title: "Around the World", artist: "Daft Punk" },
    { title: "Lose Yourself to Dance", artist: "Daft Punk" },
    { title: "Instant Crush", artist: "Daft Punk" },
    { title: "Feel Good Inc.", artist: "Gorillaz" },
    { title: "Clint Eastwood", artist: "Gorillaz" },
    { title: "Dare", artist: "Gorillaz" },
    { title: "On Melancholy Hill", artist: "Gorillaz" },
    { title: "19-2000", artist: "Gorillaz" },
    { title: "Paper Planes", artist: "M.I.A." },
    { title: "Dog Days Are Over", artist: "Florence + The Machine" },
    { title: "Shake It Out", artist: "Florence + The Machine" },
    { title: "Rolling in the Deep", artist: "Adele" },
    { title: "Someone Like You", artist: "Adele" },
    { title: "Set Fire to the Rain", artist: "Adele" },
    { title: "Hello", artist: "Adele" },
    { title: "Send My Love (To Your New Lover)", artist: "Adele" },
    { title: "Rehab", artist: "Amy Winehouse" },
    { title: "Back to Black", artist: "Amy Winehouse" },
    { title: "Valerie", artist: "Amy Winehouse" },
    { title: "You Know I'm No Good", artist: "Amy Winehouse" },
    { title: "Tears Dry on Their Own", artist: "Amy Winehouse" },
    { title: "Crazy", artist: "Gnarls Barkley" },
    { title: "Forget You", artist: "CeeLo Green" },
    { title: "Happy", artist: "Pharrell Williams" },
    { title: "Uptown Funk", artist: "Mark Ronson ft. Bruno Mars" },
    { title: "Locked Out of Heaven", artist: "Bruno Mars" },
    { title: "Treasure", artist: "Bruno Mars" },
    { title: "Just the Way You Are", artist: "Bruno Mars" },
    { title: "Grenade", artist: "Bruno Mars" },
    { title: "Blurred Lines", artist: "Robin Thicke" },
    { title: "Can't Stop the Feeling!", artist: "Justin Timberlake" },
    { title: "Mirrors", artist: "Justin Timberlake" },
    { title: "SexyBack", artist: "Justin Timberlake" },
    { title: "Cry Me a River", artist: "Justin Timberlake" },
    { title: "Rock Your Body", artist: "Justin Timberlake" },
    { title: "Toxic", artist: "Britney Spears" },
    { title: "...Baby One More Time", artist: "Britney Spears" },
    { title: "Oops!... I Did It Again", artist: "Britney Spears" },
    { title: "Crazy in Love", artist: "Beyoncé" },
    { title: "Single Ladies (Put a Ring on It)", artist: "Beyoncé" },
    { title: "Halo", artist: "Beyoncé" },
    { title: "Irreplaceable", artist: "Beyoncé" },
    { title: "Umbrella", artist: "Rihanna" },
    { title: "Diamonds", artist: "Rihanna" },
    { title: "We Found Love", artist: "Rihanna" },
    { title: "Only Girl (In the World)", artist: "Rihanna" },
    { title: "Don't Stop the Music", artist: "Rihanna" },
    { title: "Firework", artist: "Katy Perry" },
    { title: "Roar", artist: "Katy Perry" },
    { title: "Dark Horse", artist: "Katy Perry" },
    { title: "Teenage Dream", artist: "Katy Perry" },
    { title: "California Gurls", artist: "Katy Perry" },
    { title: "Poker Face", artist: "Lady Gaga" },
    { title: "Bad Romance", artist: "Lady Gaga" },
    { title: "Just Dance", artist: "Lady Gaga" },
    { title: "Born This Way", artist: "Lady Gaga" },
    { title: "Shallow", artist: "Lady Gaga & Bradley Cooper" },
    { title: "Bad Guy", artist: "Billie Eilish" },
    { title: "Ocean Eyes", artist: "Billie Eilish" },
    { title: "Everything I Wanted", artist: "Billie Eilish" },
    { title: "Happier Than Ever", artist: "Billie Eilish" },
    { title: "Lovely", artist: "Billie Eilish & Khalid" },
    { title: "Drivers License", artist: "Olivia Rodrigo" },
    { title: "Good 4 U", artist: "Olivia Rodrigo" },
    { title: "Deja Vu", artist: "Olivia Rodrigo" },
    { title: "Levitating", artist: "Dua Lipa" },
    { title: "Don't Start Now", artist: "Dua Lipa" },
    { title: "New Rules", artist: "Dua Lipa" },
    { title: "Physical", artist: "Dua Lipa" },
    { title: "Break My Heart", artist: "Dua Lipa" },
    { title: "Blinding Lights", artist: "The Weeknd" },
    { title: "Starboy", artist: "The Weeknd" },
    { title: "The Hills", artist: "The Weeknd" },
    { title: "Can't Feel My Face", artist: "The Weeknd" },
    { title: "Save Your Tears", artist: "The Weeknd" },
    { title: "Shape of You", artist: "Ed Sheeran" },
    { title: "Thinking Out Loud", artist: "Ed Sheeran" },
    { title: "Perfect", artist: "Ed Sheeran" },
    { title: "Castle on the Hill", artist: "Ed Sheeran" },
    { title: "Photograph", artist: "Ed Sheeran" },
    { title: "Someone You Loved", artist: "Lewis Capaldi" },
    { title: "Before You Go", artist: "Lewis Capaldi" },
    { title: "Shotgun", artist: "George Ezra" },
    { title: "Budapest", artist: "George Ezra" },
    { title: "Riptide", artist: "Vance Joy" },
    { title: "Ho Hey", artist: "The Lumineers" },
    { title: "Ophelia", artist: "The Lumineers" },
    { title: "Little Lion Man", artist: "Mumford & Sons" },
    { title: "I Will Wait", artist: "Mumford & Sons" },
    { title: "The Cave", artist: "Mumford & Sons" },
    { title: "Skinny Love", artist: "Bon Iver" },
    { title: "Holocene", artist: "Bon Iver" },
    { title: "Take Me to Church", artist: "Hozier" },
    { title: "Royals", artist: "Lorde" },
    { title: "Team", artist: "Lorde" },
    { title: "Green Light", artist: "Lorde" },
    { title: "Chandelier", artist: "Sia" },
    { title: "Cheap Thrills", artist: "Sia" },
    { title: "Elastic Heart", artist: "Sia" },
    { title: "Titanium", artist: "David Guetta ft. Sia" },
    { title: "Wake Me Up", artist: "Avicii" },
    { title: "Hey Brother", artist: "Avicii" },
    { title: "Levels", artist: "Avicii" },
    { title: "Waiting For Love", artist: "Avicii" },
    { title: "The Nights", artist: "Avicii" },
    { title: "Stole the Show", artist: "Kygo" },
    { title: "Firestone", artist: "Kygo" },
    { title: "Sexual Healing", artist: "Marvin Gaye" },
    { title: "Let's Get It On", artist: "Marvin Gaye" },
    { title: "What's Going On", artist: "Marvin Gaye" },
    { title: "Ain't No Mountain High Enough", artist: "Marvin Gaye & Tammi Terrell" },
    { title: "I Heard It Through the Grapevine", artist: "Marvin Gaye" },
    { title: "My Girl", artist: "The Temptations" },
    { title: "Papa Was a Rollin' Stone", artist: "The Temptations" },
    { title: "Sittin' on the Dock of the Bay", artist: "Otis Redding" },
    { title: "Try a Little Tenderness", artist: "Otis Redding" },
    { title: "Respect", artist: "Aretha Franklin" },
    { title: "Chain of Fools", artist: "Aretha Franklin" },
    { title: "Think", artist: "Aretha Franklin" },
    { title: "I Say a Little Prayer", artist: "Aretha Franklin" },
    { title: "Natural Woman", artist: "Aretha Franklin" },
    { title: "At Last", artist: "Etta James" },
    { title: "I'd Rather Go Blind", artist: "Etta James" },
    { title: "Superstition", artist: "Stevie Wonder" },
    { title: "Signed, Sealed, Delivered", artist: "Stevie Wonder" },
    { title: "Sir Duke", artist: "Stevie Wonder" },
    { title: "Isn't She Lovely", artist: "Stevie Wonder" },
    { title: "Higher Ground", artist: "Stevie Wonder" },
    { title: "Living for the City", artist: "Stevie Wonder" },
    { title: "I Wish", artist: "Stevie Wonder" },
    { title: "Master Blaster (Jammin')", artist: "Stevie Wonder" },
    { title: "Part-Time Lover", artist: "Stevie Wonder" },
    { title: "Overjoyed", artist: "Stevie Wonder" },
    { title: "Lean on Me", artist: "Bill Withers" },
    { title: "Ain't No Sunshine", artist: "Bill Withers" },
    { title: "Lovely Day", artist: "Bill Withers" },
    { title: "Just the Two of Us", artist: "Grover Washington Jr. ft. Bill Withers" },
    { title: "Let's Stay Together", artist: "Al Green" },
    { title: "Tired of Being Alone", artist: "Al Green" },
    { title: "Love and Happiness", artist: "Al Green" },
    { title: "Theme from Shaft", artist: "Isaac Hayes" },
    { title: "Move On Up", artist: "Curtis Mayfield" },
    { title: "Superfly", artist: "Curtis Mayfield" },
    { title: "Pusherman", artist: "Curtis Mayfield" },
    { title: "Freddie's Dead", artist: "Curtis Mayfield" },
    { title: "Family Affair", artist: "Sly and the Family Stone" },
    { title: "Everyday People", artist: "Sly and the Family Stone" },
    { title: "Dance to the Music", artist: "Sly and the Family Stone" },
    { title: "Hot Stuff", artist: "Donna Summer" },
    { title: "I Feel Love", artist: "Donna Summer" },
    { title: "Last Dance", artist: "Donna Summer" },
    { title: "Bad Girls", artist: "Donna Summer" },
    { title: "Le Freak", artist: "Chic" },
    { title: "Good Times", artist: "Chic" },
    { title: "Everybody Dance", artist: "Chic" },
    { title: "We Are Family", artist: "Sister Sledge" },
    { title: "He's the Greatest Dancer", artist: "Sister Sledge" },
    { title: "Thinking of You", artist: "Sister Sledge" },
    { title: "Lost in Music", artist: "Sister Sledge" },
    { title: "Rapper's Delight", artist: "The Sugarhill Gang" },
    { title: "The Message", artist: "Grandmaster Flash & The Furious Five" },
    { title: "White Lines", artist: "Grandmaster Flash & Melle Mel" },
    { title: "Planet Rock", artist: "Afrika Bambaataa" },
    { title: "Walk This Way", artist: "Run-D.M.C." },
    { title: "It's Tricky", artist: "Run-D.M.C." },
    { title: "Fight For Your Right", artist: "Beastie Boys" },
    { title: "No Sleep Till Brooklyn", artist: "Beastie Boys" },
    { title: "Sabotage", artist: "Beastie Boys" },
    { title: "Intergalactic", artist: "Beastie Boys" },
    { title: "Lose Yourself", artist: "Eminem" },
    { title: "The Real Slim Shady", artist: "Eminem" },
    { title: "Stan", artist: "Eminem" },
    { title: "Without Me", artist: "Eminem" },
    { title: "In Da Club", artist: "50 Cent" },
    { title: "Gold Digger", artist: "Kanye West" },
    { title: "Stronger", artist: "Kanye West" },
    { title: "Heartless", artist: "Kanye West" },
    { title: "Power", artist: "Kanye West" },
    { title: "Empire State of Mind", artist: "Jay-Z ft. Alicia Keys" },
    { title: "99 Problems", artist: "Jay-Z" },
    { title: "Numb/Encore", artist: "Jay-Z/Linkin Park" },
    { title: "Ms. Jackson", artist: "OutKast" },
    { title: "Hey Ya!", artist: "OutKast" },
    { title: "Roses", artist: "OutKast" },
    { title: "So Fresh, So Clean", artist: "OutKast" },
    { title: "B.O.B.", artist: "OutKast" },
    { title: "Work It", artist: "Missy Elliott" },
    { title: "Get Ur Freak On", artist: "Missy Elliott" },
    { title: "Lose Control", artist: "Missy Elliott" },
    { title: "Doo Wop (That Thing)", artist: "Lauryn Hill" },
    { title: "Ex-Factor", artist: "Lauryn Hill" },
    { title: "Killing Me Softly", artist: "Fugees" },
    { title: "Ready or Not", artist: "Fugees" },
    { title: "No Woman, No Cry", artist: "Bob Marley" },
    { title: "Three Little Birds", artist: "Bob Marley" },
    { title: "One Love", artist: "Bob Marley" },
    { title: "Redemption Song", artist: "Bob Marley" },
    { title: "Could You Be Loved", artist: "Bob Marley" },
    { title: "Jamming", artist: "Bob Marley" },
    { title: "Is This Love", artist: "Bob Marley" },
    { title: "Buffalo Soldier", artist: "Bob Marley" },
    { title: "Stir It Up", artist: "Bob Marley" },
    { title: "Get Up, Stand Up", artist: "Bob Marley" },
    { title: "I Shot the Sheriff", artist: "Bob Marley" },
    { title: "Waiting in Vain", artist: "Bob Marley" },
    { title: "Turn Your Lights Down Low", artist: "Bob Marley" },
    { title: "Satisfy My Soul", artist: "Bob Marley" },
    { title: "Exodus", artist: "Bob Marley" },
    { title: "Iron Lion Zion", artist: "Bob Marley" },
    { title: "Sun Is Shining", artist: "Bob Marley" },
    { title: "Positive Vibration", artist: "Bob Marley" },
    { title: "Kaya", artist: "Bob Marley" },
    { title: "Roots, Rock, Reggae", artist: "Bob Marley" },
    { title: "Take Five", artist: "Dave Brubeck" },
    { title: "So What", artist: "Miles Davis" },
    { title: "Blue in Green", artist: "Miles Davis" },
    { title: "All Blues", artist: "Miles Davis" },
    { title: "Fly Me to the Moon", artist: "Frank Sinatra" },
    { title: "My Way", artist: "Frank Sinatra" },
    { title: "That's Life", artist: "Frank Sinatra" },
    { title: "New York, New York", artist: "Frank Sinatra" },
    { title: "Strangers in the Night", artist: "Frank Sinatra" },
    { title: "I've Got You Under My Skin", artist: "Frank Sinatra" },
    { title: "The Way You Look Tonight", artist: "Frank Sinatra" },
    { title: "Come Fly with Me", artist: "Frank Sinatra" },
    { title: "Unforgettable", artist: "Nat King Cole" },
    { title: "L-O-V-E", artist: "Nat King Cole" },
    { title: "Smile", artist: "Nat King Cole" },
    { title: "Mona Lisa", artist: "Nat King Cole" },
    { title: "Nature Boy", artist: "Nat King Cole" },
    { title: "Stardust", artist: "Nat King Cole" },
    { title: "Autumn Leaves", artist: "Nat King Cole" },
    { title: "Route 66", artist: "Nat King Cole" },
    { title: "When I Fall in Love", artist: "Nat King Cole" },
    { title: "Georgia on My Mind", artist: "Ray Charles" },
    { title: "Hit the Road Jack", artist: "Ray Charles" },
    { title: "I Got a Woman", artist: "Ray Charles" },
    { title: "Mess Around", artist: "Ray Charles" },
    { title: "What'd I Say", artist: "Ray Charles" },
    { title: "Hallelujah I Love Her So", artist: "Ray Charles" },
    { title: "Unchain My Heart", artist: "Ray Charles" },
    { title: "Crying Time", artist: "Ray Charles" },
    { title: "Night Time Is the Right Time", artist: "Ray Charles" },
    { title: "Busted", artist: "Ray Charles" },
    { title: "A Song for You", artist: "Donny Hathaway" },
    { title: "The Ghetto", artist: "Donny Hathaway" },
    { title: "This Christmas", artist: "Donny Hathaway" },
    { title: "Someday We'll All Be Free", artist: "Donny Hathaway" },
    { title: "Giving Up", artist: "Donny Hathaway" },
    { title: "Little Ghetto Boy", artist: "Donny Hathaway" },
    { title: "Jealous Guy", artist: "Donny Hathaway" },
    { title: "I Love You More Than You'll Ever Know", artist: "Donny Hathaway" },
    { title: "You've Got a Friend", artist: "Donny Hathaway" },
    { title: "Sack Full of Dreams", artist: "Donny Hathaway" },
    { title: "Valdez in the Country", artist: "Donny Hathaway" },
    { title: "Magnificent Sanctuary Band", artist: "Donny Hathaway" },
    { title: "Sugar Lee", artist: "Donny Hathaway" },
    { title: "Flying Easy", artist: "Donny Hathaway" },
    { title: "Nu-Po", artist: "Donny Hathaway" },
    { title: "Love, Love, Love", artist: "Donny Hathaway" },
    { title: "He Ain't Heavy, He's My Brother", artist: "Donny Hathaway" },
    { title: "Voices Inside (Everything Is Everything)", artist: "Donny Hathaway" },
    { title: "Thank You Master (For My Soul)", artist: "Donny Hathaway" },
    { title: "To Be Young, Gifted and Black", artist: "Donny Hathaway" },
    { title: "Put Your Hand in the Hand", artist: "Donny Hathaway" },
    { title: "I Believe to My Soul", artist: "Donny Hathaway" },
    { title: "Misty", artist: "Donny Hathaway" },
    { title: "Come Little Children", artist: "Donny Hathaway" },
    { title: "Take a Letter Maria", artist: "Donny Hathaway" },
    { title: "Baby I Love You", artist: "Aretha Franklin" },
    { title: "(You Make Me Feel Like) A Natural Woman", artist: "Aretha Franklin" },
    { title: "Do Right Woman, Do Right Man", artist: "Aretha Franklin" },
    { title: "Bridge Over Troubled Water", artist: "Aretha Franklin" },
    { title: "Spanish Harlem", artist: "Aretha Franklin" },
    { title: "Rock Steady", artist: "Aretha Franklin" },
    { title: "Day Dreaming", artist: "Aretha Franklin" },
    { title: "Until You Come Back to Me", artist: "Aretha Franklin" },
    { title: "Freeway of Love", artist: "Aretha Franklin" },
    { title: "Who's Zoomin' Who", artist: "Aretha Franklin" },
    { title: "I Knew You Were Waiting (For Me)", artist: "Aretha Franklin & George Michael" },
    { title: "Sisters Are Doin' It for Themselves", artist: "Eurythmics & Aretha Franklin" },
    { title: "Jumpin' Jack Flash", artist: "Aretha Franklin" },
    { title: "A Rose Is Still a Rose", artist: "Aretha Franklin" },
    { title: "Rolling in the Deep (Cover)", artist: "Aretha Franklin" },
    { title: "Son of a Preacher Man", artist: "Dusty Springfield" },
    { title: "I Only Want to Be with You", artist: "Dusty Springfield" },
    { title: "You Don't Have to Say You Love Me", artist: "Dusty Springfield" },
    { title: "The Look of Love", artist: "Dusty Springfield" },
    { title: "Wishin' and Hopin'", artist: "Dusty Springfield" },
    { title: "Spooky", artist: "Dusty Springfield" },
    { title: "Windmills of Your Mind", artist: "Dusty Springfield" },
    { title: "Piece of My Heart", artist: "Janis Joplin" },
    { title: "Me and Bobby McGee", artist: "Janis Joplin" },
    { title: "Mercedes Benz", artist: "Janis Joplin" },
    { title: "Cry Baby", artist: "Janis Joplin" },
    { title: "Summertime", artist: "Janis Joplin" },
    { title: "Ball and Chain", artist: "Janis Joplin" },
    { title: "Down on Me", artist: "Janis Joplin" },
    { title: "Bye Bye Baby", artist: "Janis Joplin" },
    { title: "Kozmic Blues", artist: "Janis Joplin" },
    { title: "Move Over", artist: "Janis Joplin" },
    { title: "Get It While You Can", artist: "Janis Joplin" },
    { title: "Maybe", artist: "Janis Joplin" },
    { title: "Try (Just a Little Bit Harder)", artist: "Janis Joplin" },
    { title: "Work Me, Lord", artist: "Janis Joplin" },
    { title: "Little Girl Blue", artist: "Janis Joplin" },
    { title: "Half Moon", artist: "Janis Joplin" },
    { title: "A Woman Left Lonely", artist: "Janis Joplin" },
    { title: "My Baby", artist: "Janis Joplin" },
    { title: "Trust Me", artist: "Janis Joplin" },
    { title: "Buried Alive in the Blues", artist: "Janis Joplin" },
    { title: "Flower in the Sun", artist: "Janis Joplin" },
    { title: "Turtle Blues", artist: "Janis Joplin" },
    { title: "Farewell Song", artist: "Janis Joplin" },
    { title: "Misery'n", artist: "Janis Joplin" },
    { title: "Blindia", artist: "Janis Joplin" },
    { title: "Catch Me Daddy", artist: "Janis Joplin" },
    { title: "Easy Rider", artist: "Janis Joplin" },
    { title: "Women Is Losers", artist: "Janis Joplin" },
    { title: "Light Is Faster Than Sound", artist: "Janis Joplin" },
    { title: "All Is Loneliness", artist: "Janis Joplin" },
    { title: "Call on Me", artist: "Janis Joplin" },
    { title: "Caterpillar", artist: "Janis Joplin" },
    { title: "Cod'ine", artist: "Janis Joplin" },
    { title: "The Last Time", artist: "Janis Joplin" },
    { title: "Sweet Mary", artist: "Janis Joplin" },
    { title: "Magic of Love", artist: "Janis Joplin" },
    { title: "Mary Jane", artist: "Janis Joplin" },
    { title: "What Good Can Drinkin' Do", artist: "Janis Joplin" },
    { title: "Silver Threads and Golden Needles", artist: "Janis Joplin" },
    { title: "San Francisco Bay Blues", artist: "Janis Joplin" },
    { title: "Winin' Boy Blues", artist: "Janis Joplin" },
    { title: "Careless Love", artist: "Janis Joplin" },
    { title: "I Know You Rider", artist: "Janis Joplin" },
    { title: "Moanin' at Midnight", artist: "Janis Joplin" },
    { title: "How Long Blues", artist: "Janis Joplin" },
    { title: "In the Arms of an Angel", artist: "Sarah McLachlan" }, // 365
];

export async function getDailySong(): Promise<DailySong> {
    const now = new Date();

    // Create a unique integer seed for the day: YYYYMMDD (e.g., 20251219)
    // This ensures the song stays the same for 24h but changes drastically the next day.
    const seed = now.getFullYear() * 10000 + (now.getMonth() + 1) * 100 + now.getDate();

    // Simple pseudo-random number generator (Mulberry32-style) to mix it up
    // This avoids "Song 1" always following "Song 2".
    let t = seed + 0x6D2B79F5;
    t = Math.imul(t ^ (t >>> 15), t | 1);
    t ^= t + Math.imul(t ^ (t >>> 7), t | 61);
    const randomFloat = ((t ^ (t >>> 14)) >>> 0) / 4294967296;

    const index = Math.floor(randomFloat * songs.length);
    return songs[index];
}
